package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"
	"pet-pamper/gateway/graphql/api"
	"pet-pamper/gateway/graphql/model"
)

// Create is the resolver for the create field.
func (r *productMutationResolver) Create(ctx context.Context, obj *model.ProductMutation, request model.CreateProductRequest) (bool, error) {
	panic(fmt.Errorf("not implemented: Create - create"))
}

// Get is the resolver for the get field.
func (r *productQueryResolver) Get(ctx context.Context, obj *model.ProductQuery, id string) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: Get - get"))
}

// List is the resolver for the list field.
func (r *productQueryResolver) List(ctx context.Context, obj *model.ProductQuery, request *string) (*model.ListProductResponse, error) {
	panic(fmt.Errorf("not implemented: List - list"))
}

// ProductMutation returns api.ProductMutationResolver implementation.
func (r *Resolver) ProductMutation() api.ProductMutationResolver { return &productMutationResolver{r} }

// ProductQuery returns api.ProductQueryResolver implementation.
func (r *Resolver) ProductQuery() api.ProductQueryResolver { return &productQueryResolver{r} }

type productMutationResolver struct{ *Resolver }
type productQueryResolver struct{ *Resolver }
